package com.pega.schooltasklist.database.object;
// Generated Aug 2, 2015 7:51:34 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Groupuser generated by hbm2java
 */
public class Groupuser  implements java.io.Serializable {


     private Long id;
     private Schoolgroup schoolgroup;
     private User user;
     private Boolean active;
     private Date createDate;

    public Groupuser() {
    }

	
    public Groupuser(Schoolgroup schoolgroup, User user) {
        this.schoolgroup = schoolgroup;
        this.user = user;
    }
    public Groupuser(Schoolgroup schoolgroup, User user, Boolean active, Date createDate) {
       this.schoolgroup = schoolgroup;
       this.user = user;
       this.active = active;
       this.createDate = createDate;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Schoolgroup getSchoolgroup() {
        return this.schoolgroup;
    }
    
    public void setSchoolgroup(Schoolgroup schoolgroup) {
        this.schoolgroup = schoolgroup;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


