package com.pega.schooltasklist.database.object;
// Generated Aug 1, 2015 11:17:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private int id;
     private String name;
     private Date createDate;
     private Boolean active;
     private Set users = new HashSet(0);

    public Role() {
    }

	
    public Role(int id) {
        this.id = id;
    }
    public Role(int id, String name, Date createDate, Boolean active, Set users) {
       this.id = id;
       this.name = name;
       this.createDate = createDate;
       this.active = active;
       this.users = users;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


