package com.pega.schooltasklist.database.object;
// Generated Aug 2, 2015 6:43:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private Long id;
     private Schoolgroup schoolgroup;
     private String taskContent;
     private Date createDate;
     private Date deadline;
     private Boolean active;
     private Set taskusers = new HashSet(0);

    public Task() {
    }

    public Task(Schoolgroup schoolgroup, String taskContent, Date createDate, Date deadline, Boolean active, Set taskusers) {
       this.schoolgroup = schoolgroup;
       this.taskContent = taskContent;
       this.createDate = createDate;
       this.deadline = deadline;
       this.active = active;
       this.taskusers = taskusers;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Schoolgroup getSchoolgroup() {
        return this.schoolgroup;
    }
    
    public void setSchoolgroup(Schoolgroup schoolgroup) {
        this.schoolgroup = schoolgroup;
    }
    public String getTaskContent() {
        return this.taskContent;
    }
    
    public void setTaskContent(String taskContent) {
        this.taskContent = taskContent;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set getTaskusers() {
        return this.taskusers;
    }
    
    public void setTaskusers(Set taskusers) {
        this.taskusers = taskusers;
    }




}


